### ISSUE TITLE
Performance:  POLL'ing for every function call, including...

### ISSUE THREAD

**Issue by GordonBGood** [feeley/gambit#102]
POLL'ing calls for stack maintenance checks currently are manually inserted by the Gambit compiler for every new function call, including those by tail call recursive functions that don't make any stack adjustments.  It may be to hard for simple flow analysis to determine that a given loop doesn't trigger changes in stack depth, but it would seem to me that the compiler knows when the stack is adjusted in depth as it would be issuing stack adjustment macro's.

Couldn't the checks for required stack maintenance be a part of the stack adjustment macro's since it is only at stack adjustment events that the stack might reach its set depth limits which would trigger the maintenance.  I see that there is a provision for this to be triggered (co-operatively) by a timer, but the polling of the timer is a part of these same POLL'ing routines; I also see that it isn't necessary that there be a timer (in order to support more targets that might not have one?).

These POLL'ing checks likely take two to three CPU clock cycles each (even when no maintenance is required), which could be very significant for small tight loops or say about 7.5 clock cycles otherwise (about a 33% slow down).

**Comment by gambiteer** [comment]
> On Jan 25, 2015, at 11:01 AM, GordonBGood <notifications@github.com> wrote:
> 
> POLL'ing calls for stack maintenance checks currently are manually inserted by the Gambit compiler for every new function call, including those by tail call recursive functions that don't make any stack adjustments. It may be to hard for simple flow analysis to determine that a given loop doesn't trigger changes in stack depth, but it would seem to me that the compiler knows when the stack is adjusted in depth as it would be issuing stack adjustment macro's.
> 
The POLLs are not just to check for stack overflow, they’re used to check whether the user has hit CNTL-C to interrupt the process and enter the debugger, because Gambit otherwise masks CNTL-C.  So if you don’t have POLLs, you can’t CNTL-C out of the job (you can still use CNTL-Z to pause it and then kill it externally if you like).

If you search for interrupts-enabled in lib/_num.scm, you’ll see places where the POLLs have been elided by hand in many loops that are known not do allocate new memory.  But if you’d doing something really big (computing a billion digits of pi, for example), there are times in the FFT code where you can notice the pause between hitting CNTL-C and gambit dropping into the debugger.

You’ve developed some good understanding about the Gambit runtime.  I think what would benefit runtime speed the most right now is (a) having a real register allocator and  (b) keeping flonums unboxed across jumps (for numerical code).  (Sometimes I get around that problem by explicitly allocating one f64vector and reading and writing its entry.)

Brad=

**Comment by feeley** [comment]
As Brad pointed out, the POLL operations serve a dual purpose: checking for stack overflow, and checking for "interrupts" (which includes CTRL-C, but also timer interrupts for preemptive scheduling of the green threads).  These POLL operations are also critical to implement proper tail calls in the universal backend (which targets JavaScript, PHP, Python and Ruby) to prevent very deeply nested calls.

**Comment by GordonBGood** [comment]
Hi Marc,

Yes, I see that in this implementation that the POLL's are necessary.

The only way to get rid of the POLL's is quite an extensive change as in
support for native threads or as per my ideas in my reply to Issue #101 at:
 https://github.com/feeley/gambit/issues/101#issuecomment-71770778.

Regards,
Gordon Goodsman
