### ISSUE TITLE
iOS version 7.0 crashes on startup on iPad mini retina (iOS 8.1.3 64-bit)

### ISSUE THREAD

**Issue by csyde** [feeley/gambit#106]
Just like it says -- it fails on an iPad mini retina (2nd generation). It works fine on my iPod touch running the same version of iOS.

**Comment by feeley** [comment]
The problem has been fixed last week, but the revised app has to go through the App Store review process before it is available on the App Store (this usually takes a week or two).  The problem was that the arm64 architecture (64 bit processor) was wrongly assumed to be big-endian. The fix is commit e36bfbe25f1c37a5a2f43cf2d3e7611a988448c3.

**Comment by csyde** [comment]
Thanks, good to know!
