### ISSUE TITLE
Regression in object->u8vector / u8vector->object

### ISSUE THREAD

**Issue by jazzscheme** [feeley/gambit#151]
At some point, a regression was introduced in object->u8vector / u8vector->object related to passing an explicit encoder / decoder. That regression was fixed in commit:

- - - - - - - - - - - - - - - - - - - - - - - -
commit 42db11005625a0f03632b46c45345d67144af21d
Author: Marc Feeley <feeley@iro.umontreal.ca>
Date:   Thu Jul 16 15:12:16 2015 -0400

    Fix u8vector->object which could pass partially initialized structures to the transform function (this is due to the circular nature of the type descriptor of type descriptors)
- - - - - - - - - - - - - - - - - - - - - - - -

In the latest commit:

- - - - - - - - - - - - - - - - - - - - - - - -
commit eff65364445d02075e4eb06dbcd0371abc777c5c
Merge: cd9d5a4 9b786ee
Author: Marc Feeley <feeley@iro.umontreal.ca>
Date:   Tue Jul 28 13:08:32 2015 -0400

    Merge pull request #149 from astlouisf/ffi

    Universal backend: new portable FFI
- - - - - - - - - - - - - - - - - - - - - - - -

the regression is back.

**Comment by feeley** [comment]
I can't reproduce this bug.  I tested the most recent Gambit using the same file that was causing problems 2 weeks ago, and it runs fine.

**Comment by gcartier** [comment]
I had the problem twice and I think the problem may be related to the build process. If I remember correctly...

#1 I was on the commit that fixed object->u8vector (42db110) and decided to try the latest, so I pulled and did a make (*not* make from-scratch as I was already on 4.7.7). The resulting gsc had the object->u8vector problem.

#2 I was playing with modifying the Gambit compiler trying out stuff and then running make, which always compiled pretty much only 1 file. At some point I decided to revert my changes by a git reset --hard and run make again. To my surprise, even though the reset had only reverted 1 file, the make started compiling tons of files. After the long compilation, the resulting gsc had the object->u8vector problem.

**Comment by feeley** [comment]
The latest release is v4.7.7.  In a "release" the .c files generated for the runtime library, interpreter and compiler are in sync with the corresponding .scm files.  This means that a single "make" is sufficient to build a consistent system (by consistent I mean that the behaviour expressed in all the .scm file of the system is the actual behaviour of the built executable library, interpreter and compiler).  For any commit after the latest release, for example the one that fixed object->u8vector, at least 2 and possibly 3 "makes" are needed, separated by "make bootstrap".  When the commits since the last release changed only library files, 2 makes are needed.  However, when the code generation behaviour of the compiler (for example gsc/_t-c-2.scm or gsc/_prims.scm) has changed, then 3 makes are needed (this is the case for the commit that fixed object->u8vector).  Note that "make from-scratch" performs the 3 "makes", so it is the safest thing to use when building Gambit from the github repo.  Fewer makes may work, but a thorough understanding of the nature of the commits since the latest release is needed to ensure that the build will work.  When in doubt "make from-scratch".

**Comment by feeley** [comment]
This issue appears to be solved, so if there is still a problem please reopen the issue.
